//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishFirm164
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catch
    {
        public int CatchID { get; set; }
        public int TripID { get; set; }
        public int SpotID { get; set; }
        public string FishType { get; set; }
        public decimal Weight { get; set; }
        public string Quality { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public System.DateTime DepartureDate { get; set; }
    
        public virtual FishingSpots FishingSpots { get; set; }
        public virtual Trips Trips { get; set; }
    }
}
