//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishFirm164
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImages
    {
        public int ImageID { get; set; }
        public int ProductID { get; set; }
        public string ImageURL { get; set; }
        public Nullable<bool> IsMain { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string AltText { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
