//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishFirm164
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteImages
    {
        public int SiteImageID { get; set; }
        public string Title { get; set; }
        public string ImageURL { get; set; }
        public string AltText { get; set; }
        public string Category { get; set; }
        public string Link { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
    }
}
