//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishFirm164
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripCrew
    {
        public int TripCrewID { get; set; }
        public int TripID { get; set; }
        public int CrewMemberID { get; set; }
    
        public virtual CrewMembers CrewMembers { get; set; }
        public virtual Trips Trips { get; set; }
    }
}
